{% set name = "nano" %}
{% set version = "2.9.7" %}
{% set major_minor = version.rpartition('.')[0] %}
{% set sha256 = "b64ab017305b1777e97b5b9b07b31db8aeebfc3e8719f61e8da1cf3866d344bd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.nano-editor.org/dist/v{{ major_minor }}/nano-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - make
    - pkg-config
  host:
    - libiconv
    - ncurses
  run:
    - libiconv
    - ncurses

test:
  commands:
    - nano -h

about:
  home: https://www.nano-editor.org/
  license: GPLv3
  license_family: GPL
  license_file: COPYING
  summary: "Nano's ANOther editor, an enhanced free Pico clone"
  description: |
    nano  is  a small and friendly editor.  It copies the look and feel of Pico, but is free software, and
    implements several features that Pico lacks, such as: opening multiple files, scrolling per line,
    undo/redo,  syntax coloring, line numbering, and soft-wrapping overlong lines.

extra:
  recipe-maintainers:
    - scopatz
