{% set name = "nano" %}
{% set version = "6.4" %}
{% set major_minor = version.rpartition('.')[0] %}
{% set sha256 = "c2deac31ba4d3fd27a42fafcc47ccf499296cc69a422bbecab63f2933ea85488" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.nano-editor.org/dist/v{{ major_minor }}/nano-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - make
    - pkg-config
  host:
    - libiconv
    - ncurses
  run:
    - libiconv
    - ncurses

test:
  commands:
    - nano -h

about:
  home: https://www.nano-editor.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: "Nano's ANOther editor, an enhanced free Pico clone"
  description: |
    nano  is  a small and friendly editor.  It copies the look and feel of Pico, but is free software, and
    implements several features that Pico lacks, such as: opening multiple files, scrolling per line,
    undo/redo,  syntax coloring, line numbering, and soft-wrapping overlong lines.
  doc_url: https://www.nano-editor.org/docs.php
  dev_url: https://git.savannah.gnu.org/cgit/nano.git/log/

extra:
  recipe-maintainers:
    - scopatz
    - matthiasdiener
