{% set name = "nano" %}
{% set version = "7.1" %}
{% set major_minor = version.rpartition('.')[0] %}
{% set sha256 = "57ba751e9b7519f0f6ddee505202e387c75dde440c1f7aa1b9310cc381406836" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.nano-editor.org/dist/v{{ major_minor }}/nano-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - gnuconfig   # [unix]
  host:
    - ncurses

test:
  commands:
    - nano -h  # [build_platform == target_platform]
    - test -f $PREFIX/bin/nano

about:
  home: https://www.nano-editor.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Nano's ANOther editor, an enhanced free Pico clone
  description: |
    nano  is  a small and friendly editor.  It copies the look and feel of Pico, but is free software, and
    implements several features that Pico lacks, such as: opening multiple files, scrolling per line,
    undo/redo,  syntax coloring, line numbering, and soft-wrapping overlong lines.
  doc_url: https://www.nano-editor.org/docs.php
  dev_url: https://git.savannah.gnu.org/cgit/nano.git/log/

extra:
  recipe-maintainers:
    - scopatz
    - matthiasdiener
