travis:
  secure:
    BINSTAR_TOKEN: VI7MXx0mW7hg31QP60IjdurfzkotqFA9FtbDni9ANeEwxFMRyvgiRD89g81NI6F32YrSAXc2z2BRIXD5mzj/H4N8uL6MjWMB1bqmHaLRxmDvDIwrMEi4wAoyPl4zR5JHmjm/6xyMhEYJruQfYWf5kDhD9Cn0KvvqyPLnyIEUkvMDM0WajKZ7IrdqmMEUfPlg6tHL0FCVFVyUOER+gVrP/jhi5GLavBYC0cjykaxG6siQy9thNAtYM4axsShvOlzQxFmko3UdvfavUKUiJdjTwo1CzXWAQfpXLcMERv0jf2YKvPGg5WOqtog9LSdx4vCORPp0CSygp7S7yYgkvitFcJeVn00lRjHPjGmPffz2JNPdUqrj82lImo+NprF6qPcr7s5zNEhntOFkfojn5cxYsapFpldf5gG8Q7ehGZylJ52dcIjpDq2269sjLoxrNdJahfo2vX61WvEjYGVEexxQPVz58bDU+p7jS108bWlI861AGdEw3XEzAwW6HgiYxDMXh8fijZ5ZkswcChT9iaqlVjmEIoPCUnyRC4OJ3BcEFUl+HNkZbdmcBBlUAnKCJtxZjDSfSLvX8YP0OEev6WusC9WvCfPngnmQBuyCktN+7Ttxhp0pZ8U0PdEc1yYDK1TE6XRRMIMjUMWjyxkY0THhMuCSU+tBxLmviAaCkFUOTR0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
