appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: s91e5OPfujHSTT5OHLFwtfxpwraVB4EtotMPo12e5xNFmOnGAoonfJgY0FLANprQJfSSAaNJ0EY9Uj948i5OBfdpArj79yll0FvD5nTenhmnNb8iEy9pDibUSBT1/vDOk9zW6pKkJPbTxz2xVtH199re/AjFLcNLhjSZ411hvp9bQAQH08EGZMcNu/MRZXsERsl1NJCnLgbVEnOHx9fUYwpXw2ISXkxO7xiXyYw/daUJFpxI5TZxur6QzWKVusO8Pls+JlKiWTLSYbV9vIIRHLiaou9i1jaC+IMGZI3BZTrwWzasWqvUAdg/5yWDSTImQX2PhiYqFl0wkEHxukO3bKoFgYfxuhUFkVbqDAo0RCQ3qw+W4IWUSrL2jBNmTvxQ3ExKOs+RlBXCYGJlCwIaLBXC+off4b1YDH8M4bGfcbumyaPKmKQGU6Btqq2Y9h6qinFvjN7KOnkQutCFbT6UHJG5Lp0HtT//a6Gi67DSU/fNOZaP0ljyfJyMwFd6H/tuzRpoPvqBQ4K6iaW6N3zZ+8dVmeFe+SUY20pSPvlUEUwftnExFqj4hNqTZ63z/pno4hLOkzHZewGjoDyaNELJVZhxFjDSdblhJE9kdbtVIh7CerCWSCh0aHJJAABWIIIasa7rJJgJHn2plcNsAXkSVu3/+TPdjTyVcA1NUF/QW3A=}
conda_forge_output_validation: true
